- name: app set-up
  ansible.builtin.import_role:
    name: comman
    tasks_from: app-setup.yaml


- name: app set-up
  ansible.builtin.import_role:
    name: comman
    tasks_from: node-js setup

- name: mongodb setup
  ansible.builtin.import_role:
    name: comman
    tasks_from: mongodb-setup.yaml
  

