  
- name: deamon realod and start
  ansible.builtin.systemd_service:
    daemon_reload: true
  
- name: start and enable {{component}}
  ansible.builtin.service:
    name: {{component}}
    state: restarted
    enabled: yes